# Generated by Django 5.0.1 on 2024-05-17 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_alter_transaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_payment_success',
            field=models.BooleanField(default=False),
        ),
    ]
